name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Spring Boot Application
        working-directory: app
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t manoranjanp0729/cicd-demo:latest -f docker/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push manoranjanp0729/cicd-demo:latest
